## Put comments here that give an overall description of what your
## functions do

## Pass a matrix variable to create a list of the following four functions:
## 1. set the value of the matrix
## 2. get the value of the matrix
## 3. set the value of the inverse of the matrix
## 4. get the value of the inverse of the matirx

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y){
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinv <- function(inv_matrix) inv <<- inv_matrix
    getinv <- function() inv
    list(set = set, get = get, 
         setinv = setinv, getinv = getinv)
}


## Calculate the inverse of a matrix with the function above
## Pass a special list variable generated by the function above
## check if the inverse of the matirx has been calculated
## if true, return the existing value of the inverse of the matirx
## if false, calculate the value of the inverse of the matrix and return it

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    inv <- x$getinv()
    if (!is.null(inv)) {
        message('getting cached data')
        return(inv)
    }
    data <- x$get()
    inv <- solve(data)
    x$setinv(inv)
    inv
}
